scale_cal:
  zero_cal:
    empty: 158372.1
    small: 16595.45
    large: -53954.925
  cal_value: # cal at 200ml/g
    empty: -1068644.3910256408
    small: -829068.15920398
    large: -704821.375
syrup_cal: # ml/s
- 0.982
- 0.827
- 0.956
- 1.109
- 0.942
- 0.976
- 1.061
- 1.016
flavors:
- icon: coke.png
  name: Coke
  size: 5
  pour:
    - large: 100
    - small: 50
- icon: barqs.png
  name: Barqs
  size: 2.5
  pour:
    - large: 100
    - small: 50
- icon: mello.png
  name: Mello Yellow
  size: 2.5
  pour:
    - large: 100
    - small: 50
- icon: nc.png
  name: NC
  size: 0
  pour:
    - large: 100
    - small: 50
- icon: nc.png
  name: NC
  size: 0
  pour:
    - large: 100
    - small: 50
- icon: nc.png
  name: NC
  size: 0
  pour:
    - large: 100
    - small: 50
- icon: nc.png
  name: NC
  size: 0
  pour:
    - large: 100
    - small: 50
- icon: nc.png
  name: NC
  size: 0
  pour:
    - large: 100
    - small: 50
