scale_cal:
  zero_cal:
    empty: 296913.8875 
    small: 296913.8875
    large: 296913.8875
  cal_value: # cal at 200ml/g
    empty: -919990.916998012
    small: -919990.916998012
    large: -919990.916998012
syrup_cal: # ml/s
- 840
- 1060
- 840
- 400
- 400
- 400
- 400
- 400
flavors:
- icon: coke.png
  name: Coke
  size: 5
  pour:
    - large: 160
    - small: 90
- icon: barqs.png
  name: Barqs
  size: 2.5
  pour:
    - large: 160
    - small: 90
- icon: mello.png
  name: Mello Yellow
  size: 2.5
  pour:
    - large: 160
    - small: 90
- icon: nc.png
  name: NC
  size: 0
  pour:
    - large: 100
    - small: 50
- icon: nc.png
  name: NC
  size: 0
  pour:
    - large: 100
    - small: 50
- icon: nc.png
  name: NC
  size: 0
  pour:
    - large: 100
    - small: 50
- icon: nc.png
  name: NC
  size: 0
  pour:
    - large: 100
    - small: 50
- icon: nc.png
  name: NC
  size: 0
  pour:
    - large: 100
    - small: 50
