scale_cal:
  zero_cal:
    empty: -591103.9125
    small: -637471.2375
    large: -678571.225
  cal_value: # cal at 200ml/g
    empty: -542639.8323615161
    small: -530843.7817258883
    large: -342012.1173469388
syrup_cal: # ml/s
- 330
- 330
- 330
- 330
- 330
- 330
- 330
- 330
flavors:
- icon: coke.png
  name: Coke
  size: 5
  pour:
    - large: 100
    - small: 50
- icon: barqs.png
  name: Barqs
  size: 2.5
  pour:
    - large: 100
    - small: 50
- icon: mello.png
  name: Mello Yellow
  size: 2.5
  pour:
    - large: 100
    - small: 50
- icon: nc.png
  name: NC
  size: 0
  pour:
    - large: 100
    - small: 50
- icon: nc.png
  name: NC
  size: 0
  pour:
    - large: 100
    - small: 50
- icon: nc.png
  name: NC
  size: 0
  pour:
    - large: 100
    - small: 50
- icon: nc.png
  name: NC
  size: 0
  pour:
    - large: 100
    - small: 50
- icon: nc.png
  name: NC
  size: 0
  pour:
    - large: 100
    - small: 50
